services:
  cpe:
    build: .
    environment:
      - ROUTER_PASSWORD
    pid: host
    ports:
      - 8000:8000
    privileged: true
    restart: on-failure

  prom:
    image: prom/prometheus
    links:
      - cpe
    ports:
      - 9090:9090
    restart: on-failure
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
