services:
  cpe:
    build: .
    environment:
      - ROUTER_PASSWORD
    pid: host
    ports:
      - 8000:8000
    privileged: true
    restart: always

  prom:
    image: prom/prometheus
    links:
      - cpe
    ports:
      - 9090:9090
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  newrelic-infra:
    image: newrelic/infrastructure:latest
    cap_add:
      - SYS_PTRACE
    environment:
      - NRIA_LICENSE_KEY
    network_mode: host
    pid: host
    privileged: true
    restart: always
    volumes:
      - /:/host:ro
      - /var/run/docker.sock:/var/run/docker.sock
